//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIWT.Resources.Localization.MainModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDIWT.Resources.Localization.MainModule.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Point.
        /// </summary>
        public static string ActionPoint {
            get {
                return ResourceManager.GetString("ActionPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Earthquake Adjustment Factor.
        /// </summary>
        public static string AntiEarthquakeAdjustmentFactor {
            get {
                return ResourceManager.GetString("AntiEarthquakeAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Earthquake Intensity.
        /// </summary>
        public static string AntiEarthquakeIntensity {
            get {
                return ResourceManager.GetString("AntiEarthquakeIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast In-Situ Grounting Pile.
        /// </summary>
        public static string BCPileType_CastInSituAfterGrountingPile {
            get {
                return ResourceManager.GetString("BCPileType_CastInSituAfterGrountingPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast In-Situ Pile.
        /// </summary>
        public static string BCPileType_CastInSituPile {
            get {
                return ResourceManager.GetString("BCPileType_CastInSituPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driven Pile With Sealed End.
        /// </summary>
        public static string BCPileType_DrivenPileWithSealedEnd {
            get {
                return ResourceManager.GetString("BCPileType_DrivenPileWithSealedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tube Pile or Steel Pile.
        /// </summary>
        public static string BCPileType_TubePileOrSteelPile {
            get {
                return ResourceManager.GetString("BCPileType_TubePileOrSteelPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing Capacity Window.
        /// </summary>
        public static string BearingCapacityWindow {
            get {
                return ResourceManager.GetString("BearingCapacityWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Coefficient.
        /// </summary>
        public static string BlockCoefficient {
            get {
                return ResourceManager.GetString("BlockCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Elevation.
        /// </summary>
        public static string BottomElevation {
            get {
                return ResourceManager.GetString("BottomElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Up Soil Layer Library.
        /// </summary>
        public static string BuildUpSoilLayerLib {
            get {
                return ResourceManager.GetString("BuildUpSoilLayerLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Item Name.
        /// </summary>
        public static string CalculatedItemName {
            get {
                return ResourceManager.GetString("CalculatedItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Parameters.
        /// </summary>
        public static string CalculatedParameters {
            get {
                return ResourceManager.GetString("CalculatedParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Results.
        /// </summary>
        public static string CalculatedResults {
            get {
                return ResourceManager.GetString("CalculatedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Waterlevel.
        /// </summary>
        public static string CalculatedWaterLevel {
            get {
                return ResourceManager.GetString("CalculatedWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Coefficients.
        /// </summary>
        public static string CalculationCoefficients {
            get {
                return ResourceManager.GetString("CalculationCoefficients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Date.
        /// </summary>
        public static string CheckDate {
            get {
                return ResourceManager.GetString("CheckDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checker.
        /// </summary>
        public static string Checker {
            get {
                return ResourceManager.GetString("Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete.
        /// </summary>
        public static string Concrete {
            get {
                return ResourceManager.GetString("Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete Core Length.
        /// </summary>
        public static string ConcreteCoreLength {
            get {
                return ResourceManager.GetString("ConcreteCoreLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Pile.
        /// </summary>
        public static string CreatePile {
            get {
                return ResourceManager.GetString("CreatePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Force Calculation.
        /// </summary>
        public static string CurrentForceCalculation {
            get {
                return ResourceManager.GetString("CurrentForceCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Force Standard Value.
        /// </summary>
        public static string CurrentForceStandardValue {
            get {
                return ResourceManager.GetString("CurrentForceStandardValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Resistent Coeff.
        /// </summary>
        public static string CurrentResistentCoeff {
            get {
                return ResourceManager.GetString("CurrentResistentCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Velocity.
        /// </summary>
        public static string CurrentVelocity {
            get {
                return ResourceManager.GetString("CurrentVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Pile.
        /// </summary>
        public static string DeletePile {
            get {
                return ResourceManager.GetString("DeletePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Axial Bearing Capacity of Single Pile.
        /// </summary>
        public static string DesignAxialBearingCapacity {
            get {
                return ResourceManager.GetString("DesignAxialBearingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Axial Uplift Capacity of Single Pile.
        /// </summary>
        public static string DesignAxialUpliftCapacity {
            get {
                return ResourceManager.GetString("DesignAxialUpliftCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Date.
        /// </summary>
        public static string DesignDate {
            get {
                return ResourceManager.GetString("DesignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        public static string Designer {
            get {
                return ResourceManager.GetString("Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Water Level.
        /// </summary>
        public static string DesignWaterLevel {
            get {
                return ResourceManager.GetString("DesignWaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Coefficient.
        /// </summary>
        public static string DiscountCoefficient {
            get {
                return ResourceManager.GetString("DiscountCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Resistance Value.
        /// </summary>
        public static string EndResistanceStandardValue {
            get {
                return ResourceManager.GetString("EndResistanceStandardValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File.
        /// </summary>
        public static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File(*.xlsx)|*.xlsx.
        /// </summary>
        public static string ExcelFileFilter {
            get {
                return ResourceManager.GetString("ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Depth Factorη.
        /// </summary>
        public static string FixedDepthFactor {
            get {
                return ResourceManager.GetString("FixedDepthFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Coeffs.
        /// </summary>
        public static string ForceCoeffs {
            get {
                return ResourceManager.GetString("ForceCoeffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Front Row.
        /// </summary>
        public static string FrontRow {
            get {
                return ResourceManager.GetString("FrontRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Calculation Note.
        /// </summary>
        public static string GenerateCalculationNote {
            get {
                return ResourceManager.GetString("GenerateCalculationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Information.
        /// </summary>
        public static string GeometryInformation {
            get {
                return ResourceManager.GetString("GeometryInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravitational Acceleration.
        /// </summary>
        public static string GravitationalAcceleration {
            get {
                return ResourceManager.GetString("GravitationalAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAT.
        /// </summary>
        public static string HAT {
            get {
                return ResourceManager.GetString("HAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Affect Coeff.
        /// </summary>
        public static string HorizontalAffectCoeff {
            get {
                return ResourceManager.GetString("HorizontalAffectCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Pile Centra Span.
        /// </summary>
        public static string HorizontalPileCentraSpan {
            get {
                return ResourceManager.GetString("HorizontalPileCentraSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From File.
        /// </summary>
        public static string ImportFromFile {
            get {
                return ResourceManager.GetString("ImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclining Affect Coeff.
        /// </summary>
        public static string IncliningAffectCoeff {
            get {
                return ResourceManager.GetString("IncliningAffectCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Parameters.
        /// </summary>
        public static string InputParameters {
            get {
                return ResourceManager.GetString("InputParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Pile Parameters.
        /// </summary>
        public static string InputPileParameters {
            get {
                return ResourceManager.GetString("InputPileParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Soil Layer Parameters.
        /// </summary>
        public static string InputSoilLayerParameters {
            get {
                return ResourceManager.GetString("InputSoilLayerParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Filled With Concrete.
        /// </summary>
        public static string IsFilledWithConcrete {
            get {
                return ResourceManager.GetString("IsFilledWithConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Vertical Pile.
        /// </summary>
        public static string IsVerticalPile {
            get {
                return ResourceManager.GetString("IsVerticalPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAT.
        /// </summary>
        public static string LAT {
            get {
                return ResourceManager.GetString("LAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer Top Elevation(m).
        /// </summary>
        public static string LayerTopElevation {
            get {
                return ResourceManager.GetString("LayerTopElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load From Model.
        /// </summary>
        public static string LoadFromModel {
            get {
                return ResourceManager.GetString("LoadFromModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Parameters.
        /// </summary>
        public static string LoadParameters {
            get {
                return ResourceManager.GetString("LoadParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Inforamtion.
        /// </summary>
        public static string MaterialInformation {
            get {
                return ResourceManager.GetString("MaterialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MHW.
        /// </summary>
        public static string MHW {
            get {
                return ResourceManager.GetString("MHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLW.
        /// </summary>
        public static string MLW {
            get {
                return ResourceManager.GetString("MLW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus(E).
        /// </summary>
        public static string Modulus {
            get {
                return ResourceManager.GetString("Modulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSL.
        /// </summary>
        public static string MSL {
            get {
                return ResourceManager.GetString("MSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exist in library, please correct it!.
        /// </summary>
        public static string Note_EEIL {
            get {
                return ResourceManager.GetString("Note_EEIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) For driven pile: 1.45~1.55; 2) For cast in-situ pile: 1.55~1.65.
        /// </summary>
        public static string Note_PartialCoeff {
            get {
                return ResourceManager.GetString("Note_PartialCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select pile!.
        /// </summary>
        public static string Note_PSP {
            get {
                return ResourceManager.GetString("Note_PSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Volume.
        /// </summary>
        public static string NumberOfVolume {
            get {
                return ResourceManager.GetString("NumberOfVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Coefficient.
        /// </summary>
        public static string PartialCoefficient {
            get {
                return ResourceManager.GetString("PartialCoefficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHC Tube Pile.
        /// </summary>
        public static string PHCTubePile {
            get {
                return ResourceManager.GetString("PHCTubePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picked.
        /// </summary>
        public static string Picked {
            get {
                return ResourceManager.GetString("Picked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up Soil Layers From Lib.
        /// </summary>
        public static string PickupSoilLayersFromLib {
            get {
                return ResourceManager.GetString("PickupSoilLayersFromLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Basic Inforamtion.
        /// </summary>
        public static string PileBasicInformation {
            get {
                return ResourceManager.GetString("PileBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Bottom Elevation.
        /// </summary>
        public static string PileBottomElevation {
            get {
                return ResourceManager.GetString("PileBottomElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Bottom Point.
        /// </summary>
        public static string PileBottomPoint {
            get {
                return ResourceManager.GetString("PileBottomPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Centra Span.
        /// </summary>
        public static string PileCentraSpan {
            get {
                return ResourceManager.GetString("PileCentraSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Cross Section Area.
        /// </summary>
        public static string PileCrossSectionArea {
            get {
                return ResourceManager.GetString("PileCrossSectionArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Diameter.
        /// </summary>
        public static string PileDiameter {
            get {
                return ResourceManager.GetString("PileDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Geometry Type.
        /// </summary>
        public static string PileGeoType {
            get {
                return ResourceManager.GetString("PileGeoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Inside Diameter.
        /// </summary>
        public static string PileInsideDiameter {
            get {
                return ResourceManager.GetString("PileInsideDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Length.
        /// </summary>
        public static string PileLength {
            get {
                return ResourceManager.GetString("PileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Length Calculation Window.
        /// </summary>
        public static string PileLengthCalWindow {
            get {
                return ResourceManager.GetString("PileLengthCalWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile length Modulus.
        /// </summary>
        public static string PileLengthModulus {
            get {
                return ResourceManager.GetString("PileLengthModulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile List.
        /// </summary>
        public static string PileList {
            get {
                return ResourceManager.GetString("PileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Name.
        /// </summary>
        public static string PileName {
            get {
                return ResourceManager.GetString("PileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Number.
        /// </summary>
        public static string PileNumber {
            get {
                return ResourceManager.GetString("PileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Parameters.
        /// </summary>
        public static string PileParameters {
            get {
                return ResourceManager.GetString("PileParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Perimeter.
        /// </summary>
        public static string PilePerimeter {
            get {
                return ResourceManager.GetString("PilePerimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Placement Tool.
        /// </summary>
        public static string PilePlacementTool {
            get {
                return ResourceManager.GetString("PilePlacementTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Self Weight.
        /// </summary>
        public static string PileSelfWeight {
            get {
                return ResourceManager.GetString("PileSelfWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Skewness.
        /// </summary>
        public static string PileSkewness {
            get {
                return ResourceManager.GetString("PileSkewness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Spatial Inforamtion.
        /// </summary>
        public static string PileSpatialInformation {
            get {
                return ResourceManager.GetString("PileSpatialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Board.
        /// </summary>
        public static string PileTip_DoubleBoard {
            get {
                return ResourceManager.GetString("PileTip_DoubleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Seal.
        /// </summary>
        public static string PileTip_HalfSeal {
            get {
                return ResourceManager.GetString("PileTip_HalfSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadruple Board.
        /// </summary>
        public static string PileTip_QuadBoard {
            get {
                return ResourceManager.GetString("PileTip_QuadBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Board.
        /// </summary>
        public static string PileTip_SingleBorad {
            get {
                return ResourceManager.GetString("PileTip_SingleBorad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Seal.
        /// </summary>
        public static string PileTip_TotalSeal {
            get {
                return ResourceManager.GetString("PileTip_TotalSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Tip Seal Type.
        /// </summary>
        public static string PileTipSealType {
            get {
                return ResourceManager.GetString("PileTipSealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Top Elevation.
        /// </summary>
        public static string PileTopElevation {
            get {
                return ResourceManager.GetString("PileTopElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Top Point.
        /// </summary>
        public static string PileTopPoint {
            get {
                return ResourceManager.GetString("PileTopPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Type.
        /// </summary>
        public static string PileType {
            get {
                return ResourceManager.GetString("PileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Type Illustration.
        /// </summary>
        public static string PileTypeIllustration {
            get {
                return ResourceManager.GetString("PileTypeIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Weight Partial Factor.
        /// </summary>
        public static string PileWeightPartialFactor {
            get {
                return ResourceManager.GetString("PileWeightPartialFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Width(Pile Outside Diameter).
        /// </summary>
        public static string PileWidth {
            get {
                return ResourceManager.GetString("PileWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Workmanship Type.
        /// </summary>
        public static string PileWorkmanshipType {
            get {
                return ResourceManager.GetString("PileWorkmanshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poisson(γ).
        /// </summary>
        public static string Poisson {
            get {
                return ResourceManager.GetString("Poisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction Design.
        /// </summary>
        public static string PP_ConstructionDesign {
            get {
                return ResourceManager.GetString("PP_ConstructionDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feasibility Study.
        /// </summary>
        public static string PP_FeasibilityStudy {
            get {
                return ResourceManager.GetString("PP_FeasibilityStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Design.
        /// </summary>
        public static string PP_PreliminaryDesign {
            get {
                return ResourceManager.GetString("PP_PreliminaryDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preliminary Feasibility Study.
        /// </summary>
        public static string PP_PreliminaryFeasibilityStudy {
            get {
                return ResourceManager.GetString("PP_PreliminaryFeasibilityStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Area.
        /// </summary>
        public static string ProjectedArea {
            get {
                return ResourceManager.GetString("ProjectedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected Width.
        /// </summary>
        public static string ProjectedWidth {
            get {
                return ResourceManager.GetString("ProjectedWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Phase.
        /// </summary>
        public static string ProjectPhase {
            get {
                return ResourceManager.GetString("ProjectPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear Row.
        /// </summary>
        public static string RearRow {
            get {
                return ResourceManager.GetString("RearRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generator.
        /// </summary>
        public static string ReportGenerator {
            get {
                return ResourceManager.GetString("ReportGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Date.
        /// </summary>
        public static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewer.
        /// </summary>
        public static string Reviewer {
            get {
                return ResourceManager.GetString("Reviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Pile.
        /// </summary>
        public static string RoundPile {
            get {
                return ResourceManager.GetString("RoundPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Bed Elevation.
        /// </summary>
        public static string SeabedElevation {
            get {
                return ResourceManager.GetString("SeabedElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setttings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheltering Coeff.
        /// </summary>
        public static string ShelteringCoeff {
            get {
                return ResourceManager.GetString("ShelteringCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Curve.
        /// </summary>
        public static string ShowPileLengthBCCurve {
            get {
                return ResourceManager.GetString("ShowPileLengthBCCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Friction Value.
        /// </summary>
        public static string SideFrictionStandardValue {
            get {
                return ResourceManager.GetString("SideFrictionStandardValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Length / Diameter.
        /// </summary>
        public static string SideLengthDiameter {
            get {
                return ResourceManager.GetString("SideLengthDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Layer Name.
        /// </summary>
        public static string SoilLayerName {
            get {
                return ResourceManager.GetString("SoilLayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Layer Number.
        /// </summary>
        public static string SoilLayerNumber {
            get {
                return ResourceManager.GetString("SoilLayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Layers Library.
        /// </summary>
        public static string SoilLayersLibrary {
            get {
                return ResourceManager.GetString("SoilLayersLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Layer Thickness.
        /// </summary>
        public static string SoilLayerThickness {
            get {
                return ResourceManager.GetString("SoilLayerThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Parameters.
        /// </summary>
        public static string SoilParameters {
            get {
                return ResourceManager.GetString("SoilParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Pile.
        /// </summary>
        public static string SquarePile {
            get {
                return ResourceManager.GetString("SquarePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staad File.
        /// </summary>
        public static string StaadFile {
            get {
                return ResourceManager.GetString("StaadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staad File(*.std)|*.std.
        /// </summary>
        public static string StaadFileFilter {
            get {
                return ResourceManager.GetString("StaadFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Tube Pile.
        /// </summary>
        public static string SteelTubePile {
            get {
                return ResourceManager.GetString("SteelTubePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Importance Factoer.
        /// </summary>
        public static string StructureImportanceFactor {
            get {
                return ResourceManager.GetString("StructureImportanceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submerged Coeff.
        /// </summary>
        public static string SubmergedCoeff {
            get {
                return ResourceManager.GetString("SubmergedCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Bearing Capacity EC Instance.
        /// </summary>
        public static string TN_AttachBCEC {
            get {
                return ResourceManager.GetString("TN_AttachBCEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Elevation.
        /// </summary>
        public static string TopElevation {
            get {
                return ResourceManager.GetString("TopElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Pile.
        /// </summary>
        public static string TubePile {
            get {
                return ResourceManager.GetString("TubePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnderWater Unit Weight.
        /// </summary>
        public static string UnderWaterUnitWeight {
            get {
                return ResourceManager.GetString("UnderWaterUnitWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Force Coefficient(CD).
        /// </summary>
        public static string VelocityForceCoeffCD {
            get {
                return ResourceManager.GetString("VelocityForceCoeffCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocity Force Coefficient(CM).
        /// </summary>
        public static string VelocityForceCoeffCM {
            get {
                return ResourceManager.GetString("VelocityForceCoeffCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Pile Centra Span.
        /// </summary>
        public static string VerticalPileCentraSpan {
            get {
                return ResourceManager.GetString("VerticalPileCentraSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Density.
        /// </summary>
        public static string WaterDensity {
            get {
                return ResourceManager.GetString("WaterDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Depth d(m).
        /// </summary>
        public static string WaterDepth {
            get {
                return ResourceManager.GetString("WaterDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Depth Coeff.
        /// </summary>
        public static string WaterDepthCoeff {
            get {
                return ResourceManager.GetString("WaterDepthCoeff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterLevel.
        /// </summary>
        public static string WaterLevel {
            get {
                return ResourceManager.GetString("WaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Weight.
        /// </summary>
        public static string WaterWeight {
            get {
                return ResourceManager.GetString("WaterWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave.
        /// </summary>
        public static string Wave {
            get {
                return ResourceManager.GetString("Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Action Force for Pile and Pier Structure.
        /// </summary>
        public static string WaveForceWindowTitle {
            get {
                return ResourceManager.GetString("WaveForceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Height(H).
        /// </summary>
        public static string WaveHeight {
            get {
                return ResourceManager.GetString("WaveHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Length(L).
        /// </summary>
        public static string WaveLength {
            get {
                return ResourceManager.GetString("WaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Parameters.
        /// </summary>
        public static string WaveParameters {
            get {
                return ResourceManager.GetString("WaveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Period(Tp).
        /// </summary>
        public static string WavePeriod {
            get {
                return ResourceManager.GetString("WavePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Elevation.
        /// </summary>
        public static string WharfElevation {
            get {
                return ResourceManager.GetString("WharfElevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word(*.docx)|*.docx.
        /// </summary>
        public static string WordFileFilter {
            get {
                return ResourceManager.GetString("WordFileFilter", resourceCulture);
            }
        }
    }
}
