//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIWT.Resources.Localization.MainModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDIWT.Resources.Localization.MainModule.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Earthquake Adjustment Factor.
        /// </summary>
        public static string AntiEarthquakeAdjustmentFactor {
            get {
                return ResourceManager.GetString("AntiEarthquakeAdjustmentFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Earthquake Intensity.
        /// </summary>
        public static string AntiEarthquakeIntensity {
            get {
                return ResourceManager.GetString("AntiEarthquakeIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice.
        /// </summary>
        public static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete.
        /// </summary>
        public static string Concrete {
            get {
                return ResourceManager.GetString("Concrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete Core Length.
        /// </summary>
        public static string ConcreteCoreLength {
            get {
                return ResourceManager.GetString("ConcreteCoreLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File.
        /// </summary>
        public static string ExcelFile {
            get {
                return ResourceManager.GetString("ExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel File(*.xlsx)|*.xlsx.
        /// </summary>
        public static string ExcelFileFilter {
            get {
                return ResourceManager.GetString("ExcelFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Depth Factorη.
        /// </summary>
        public static string FixedDepthFactor {
            get {
                return ResourceManager.GetString("FixedDepthFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string Geometry {
            get {
                return ResourceManager.GetString("Geometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import From File.
        /// </summary>
        public static string ImportFromFile {
            get {
                return ResourceManager.GetString("ImportFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Filled With Concrete.
        /// </summary>
        public static string IsFilledWithConcrete {
            get {
                return ResourceManager.GetString("IsFilledWithConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulus(E).
        /// </summary>
        public static string Modulus {
            get {
                return ResourceManager.GetString("Modulus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHC Tube Pile.
        /// </summary>
        public static string PHCTubePile {
            get {
                return ResourceManager.GetString("PHCTubePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Basic Inforamtion.
        /// </summary>
        public static string PileBasicInformation {
            get {
                return ResourceManager.GetString("PileBasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Point.
        /// </summary>
        public static string PileBottomPoint {
            get {
                return ResourceManager.GetString("PileBottomPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Inside Diameter.
        /// </summary>
        public static string PileInsideDiameter {
            get {
                return ResourceManager.GetString("PileInsideDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Number.
        /// </summary>
        public static string PileNumber {
            get {
                return ResourceManager.GetString("PileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Spatial Inforamtion.
        /// </summary>
        public static string PileSpatialInformation {
            get {
                return ResourceManager.GetString("PileSpatialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Board.
        /// </summary>
        public static string PileTip_DoubleBoard {
            get {
                return ResourceManager.GetString("PileTip_DoubleBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Seal.
        /// </summary>
        public static string PileTip_HalfSeal {
            get {
                return ResourceManager.GetString("PileTip_HalfSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadruple Board.
        /// </summary>
        public static string PileTip_QuadBoard {
            get {
                return ResourceManager.GetString("PileTip_QuadBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Board.
        /// </summary>
        public static string PileTip_SingleBorad {
            get {
                return ResourceManager.GetString("PileTip_SingleBorad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Seal.
        /// </summary>
        public static string PileTip_TotalSeal {
            get {
                return ResourceManager.GetString("PileTip_TotalSeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Tip Seal Type.
        /// </summary>
        public static string PileTipSealType {
            get {
                return ResourceManager.GetString("PileTipSealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Point.
        /// </summary>
        public static string PileTopPoint {
            get {
                return ResourceManager.GetString("PileTopPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Type.
        /// </summary>
        public static string PileType {
            get {
                return ResourceManager.GetString("PileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Type Illustration.
        /// </summary>
        public static string PileTypeIllustration {
            get {
                return ResourceManager.GetString("PileTypeIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Weight Partial Factor.
        /// </summary>
        public static string PileWeightPartialFactor {
            get {
                return ResourceManager.GetString("PileWeightPartialFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile Width(Pile Outside Diameter).
        /// </summary>
        public static string PileWidth {
            get {
                return ResourceManager.GetString("PileWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poisson(γ).
        /// </summary>
        public static string Poisson {
            get {
                return ResourceManager.GetString("Poisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setttings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Length / Diameter.
        /// </summary>
        public static string SideLengthDiameter {
            get {
                return ResourceManager.GetString("SideLengthDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Pile.
        /// </summary>
        public static string SquarePile {
            get {
                return ResourceManager.GetString("SquarePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staad File.
        /// </summary>
        public static string StaadFile {
            get {
                return ResourceManager.GetString("StaadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staad File(*.std)|*.std.
        /// </summary>
        public static string StaadFileFilter {
            get {
                return ResourceManager.GetString("StaadFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel.
        /// </summary>
        public static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steel Tube Pile.
        /// </summary>
        public static string SteelTubePile {
            get {
                return ResourceManager.GetString("SteelTubePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Importance Factoer.
        /// </summary>
        public static string StructureImportanceFactor {
            get {
                return ResourceManager.GetString("StructureImportanceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tube Pile.
        /// </summary>
        public static string TubePile {
            get {
                return ResourceManager.GetString("TubePile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnderWater Density.
        /// </summary>
        public static string UnderWaterDensity {
            get {
                return ResourceManager.GetString("UnderWaterDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaterLevel.
        /// </summary>
        public static string WaterLevel {
            get {
                return ResourceManager.GetString("WaterLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave.
        /// </summary>
        public static string Wave {
            get {
                return ResourceManager.GetString("Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Height(H).
        /// </summary>
        public static string WaveHeight {
            get {
                return ResourceManager.GetString("WaveHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Length(L).
        /// </summary>
        public static string WaveLength {
            get {
                return ResourceManager.GetString("WaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Period(Tp).
        /// </summary>
        public static string WavePeriod {
            get {
                return ResourceManager.GetString("WavePeriod", resourceCulture);
            }
        }
    }
}
